name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Hier kannst du weitere Versionen hinzufügen, z.B. "3.11", "3.13"
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.9.4
      with:
        # Nutzt deine pyproject.toml
        cache: true
        # Erzwingt die Version aus der Matrix (überschreibt die Standard-Version)
        python-version: ${{ matrix.python-version }}
        # locked: true setzt voraus, dass du die pixi.lock eingecheckt hast
        locked: true

    - name: Update Lockfile (Optionaler Check)
      # Dieser Schritt stellt sicher, dass die Umgebung absolut frisch ist
      run: pixi update --frozen

      # Linter definiert in pyproject.toml
    - name: Lint with ruff
      run: pixi run lint

      # Test definiert in pyproject.toml
    - name: Test with pytest
      run: pixi run test
